### PR TITLE
Fix #41 - Add .NET unit tests

### LINKED ISSUE #41: Create unit tests for .NET (dotnet) bindings
Right now we do not have unit tests for the dotnet bindings:
https://github.com/google/gtfs-realtime-bindings/tree/master/dotnet

This can potentially cause issues when we update the bindings if there have been changes in the toolchain - process for updating the bindings is described here:
https://github.com/google/gtfs-realtime-bindings/blob/master/dotnet/UPDATING.md

For comparison, we currently have unit tests for the Java bindings, and the code can be seen here:
https://github.com/google/gtfs-realtime-bindings/blob/master/java/src/test/java/com/google/transit/realtime/GtfsRealtimeTest.java

...which test the consumption of a sample bundled protobuf file included in this directory:
https://github.com/google/gtfs-realtime-bindings/tree/master/java/src/test/resources/com/google/transit/realtime

These tests are run as part of the process for updating the Java bindings, as described here:
https://github.com/google/gtfs-realtime-bindings/blob/master/java/UPDATING.md

We should implement similar unit tests in the .NET bindings so we can be confident we aren't breaking anything when we update the bindings.

Sample .NET code for consuming a protobuf file can be seen in the .NET README:
https://github.com/google/gtfs-realtime-bindings/blob/master/dotnet/README.md#example-code

### PR DESCRIPTION
**Pull request by giocorti**
This PR addresses [issue 41](https://github.com/google/gtfs-realtime-bindings/issues/41) by adding unit tests for the dotnet bindings .

### CODE REVIEW

**Comment by barbeau** [comment]
@giocorti Thanks for working on this!  Could you please add instructions for how to run this unit test to the dotnet UPDATING.md file?  Also, I think the files should probably be in the `dotnet\GtfsRealtimeBindings` folder with the other .cs file (unless there is an established .NET convention I don't know about).

**Comment by barbeau** [comment]
Also, after moving the files to the above directory, when trying to run this in Visual Studio I'm getting the below error:

image

I had to add the new .cs file by right-clicking on project and "Add->Existing item", and then I get the above when I try to compile the project or run the test file.  I think this is due to the NUnit dependencies not being declared, although I tried adding them to the packages.config and that didn't seem to change anything.

**Comment by giocorti** [comment]
@barbeau Thanks for the review! I'll look into these issues and try to get them sorted out.

**Comment by giocorti** [comment]
I've made a number of changes to so that the unit tests can easily be run using command line. I've also added some instructions to UPDATING.md.

>Also, I think the files should probably be in the dotnet\GtfsRealtimeBindings folder with the other .cs file (unless there is an established .NET convention I don't know about).

I believe that moving the files to the dotnet\GtfsRealtimeBindings folder may create problems when it comes to running the code as it won't be clear to the compiler what main method is. I'm not very familiar with dotnet so I may be 100% wrong about this.

**Comment by barbeau** [comment]
Thanks @giocorti!  I think we're still missing something for the test to be integrated into the Visual Studio project, though.  When I open the .sln file in Visual Studio, I don't see the test .cs file and can't run it from there.

I'd like the final setup to be able to be automated to run from the command-line, but also to be visible and runnable from within Visual Studio if we need to make changes.

**Comment by barbeau** [comment]
Also, it looks like a number of files snuck into version control here that really shouldn't be added to the Git project, including everything in the .vs folder in root, .vs folder under "tests", and the `bin` and `obj` folders under "tests".  For starters you could copy the .gitignore from the "GtfsRealtimeBindings" folder into the "tests" folder, and I think that may cover it.  After doing this you'll still need to remove the files from version control.

**Comment by giocorti** [comment]
> Thanks @giocorti! I think we're still missing something for the test to be integrated into the Visual Studio project, though. When I open the .sln file in Visual Studio, I don't see the test .cs file and can't run it from there.

This seems to be one of those cases where things work on my machine but don't work elsewhere. When I open tests.sln I can access GtfsRealtimeTest.cs from the left hand navigation bar (see screenshot) and it runs fine for me. At some point I did have to install the relevant packages using either command line or, in Visual Studio, using "project" -> "Add NuGet Packages". 

screen shot 2019-03-08 at 10 27 18 am

I'll remove the unnecessary files and look into our Visual Studio issue some more. Sorry for all the confusion.

**Comment by barbeau** [comment]
@giocorti Oh, I was using the .sln file in the root dotnet directory (not `tests` subdirectory).  Is there a way to group this test under the main .sln file?

**Comment by giocorti** [comment]
Those latest commits should allow GtfsRealtimeTest.cs to be run from GtfsRealtimeBindings.sln.

**Comment by giocorti** [comment]
After a lot of tinkering I believe the following changes are now included in this PR:

- The unit tests can now be run from both Visual Studio and command line
- GtfsRealtimeBindings.sln can be used to access the unit tests 
- UPDATING.md has the pertinent instructions
- Unnecessary files have been removed and added to .gitignore

**Comment by barbeau** [comment]
It turns out there are breaking changes in the newer version of protobuf-net, so I updated the unit tests in this PR to comply with the new protobuf-net output and added these tests as part of the Feb 20 2019 bindings update in https://github.com/MobilityData/gtfs-realtime-bindings/pull/43.

So, I'm going to close this PR.

**Pull request closed without merging**
