### PR TITLE
Add newest version of gtfs-realtime.proto

### PR DESCRIPTION
**Pull request by leonardehrenfried**
Since this repo has been started, the proto file has received a few additions, which I'm interested in, so I added them.

Would you like me to generate the code as well or should that happen after the PR has been merged? For Java, which is what I'm interested in, I can do it easily. For the rest I'm not so sure.

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
I've also taken the liberty to add the proto-file to the JAR.

Why is that useful?

If you add it, then it will be easier to add extensions to GTFS in a downstream project as the proto file stays in sync with the Java code.

**Comment by barbeau** [comment]
@leonardehrenfried Thanks for the pull request! I'll work on generating the code after this is merged - it's a bit of a pain to get all the platforms to compile.  Adding the .proto to the JAR makes sense to me too.

How soon were you looking for this? If you can wait a week or so I'd like to include the `occupancy_percentage` field in the next release, which is being discussed here - https://github.com/google/transit/pull/213.

**Comment by leonardehrenfried** [comment]
Yes, I can wait a bit since I've deployed my fork to maven central und my own group id: https://search.maven.org/artifact/io.leonard/gtfs-realtime-bindings/0.0.7/jar

**Comment by barbeau** [comment]
@leonardehrenfried I've opened a new PR with a more up-to-date .proto at https://github.com/MobilityData/gtfs-realtime-bindings/pull/69. Thanks for this contribution, I'm including bundling the .proto in the JAR there!

**Pull request closed without merging**
