### PR TITLE
nodejs: add TS types generated using pbts

### PR DESCRIPTION
**Pull request by jameslinjl**
- Generate TypeScript types
- Add steps to re-generate types
- Edited documentation

### CODE REVIEW

**Comment by jameslinjl** [comment]
@gauthier-th if you could contribute some 👀 here

**Review by KClough — APPROVED** [review]

**Comment by KClough** [comment]
> poke @KClough @derhuerst if anyone can contribute some 👀

Sorry for the delay, lgtm.

**Comment by jameslinjl** [comment]
@isabelle-dr ready for merge as well!

cc @bdferris not sure if you were able to track down those NPM creds 😛

**Review by gauthier-th — APPROVED** [review]
lgtm

**Comment by bdferris-v2** [comment]
I did manage to dig up my credentials.  If @isabelle-dr is comfortable with it, I could add @jameslinjl as a maintainer to give you the ability to publish.  Alternatively, I could probably push a new version if needed.

**Comment by jameslinjl** [comment]
I'm good with whatever @isabelle-dr is comfortable with!

**Comment by isabelle-dr** [comment]
Thank you all for the contribution, reviews, and help with our npm situation! 
I think we need at least one MobilityData staff to be able to publish a new version of the package. So if it's relatively accessible to a nerdy product manager, I'll do this one.
If I need 4h of training to do it, then yes let's have @jameslinjl do it 😊.

**Review by isabelle-dr — APPROVED** [review]

**Pull request merged**
