### PR TITLE
feat: Update .proto as of Oct 30, 2020 and Java bindings

### PR DESCRIPTION
**Pull request by barbeau**
gtfs-realtime.proto as of https://github.com/google/transit/commit/b28d6efab405556789b724682b57802379e70932.

Also bundle .proto with Java bindings JAR as requested in #61 (comment)

Replaces https://github.com/MobilityData/gtfs-realtime-bindings/pull/67 and https://github.com/MobilityData/gtfs-realtime-bindings/pull/61.

### CODE REVIEW

**Comment by sunny-lirr** [comment]
@barbeau Is this pull request waiting on something before it can be merged?

**Comment by barbeau** [comment]
@sunny-lirr Thanks for the reminder! I was hoping to finish testing https://github.com/google/transit/pull/248 on C++ before merging this, but given that I've tested on Java and backwards compatibility doesn't seem to be an issue (and getting C++ set up is taking longer than I'd like) I'll go ahead and merge. I'll work on a release too.

**Comment by barbeau** [comment]
@sunny-lirr I just pushed `0.0.6` to Maven Central - please give it at least a few hours to show up and then give it a shot and let me know if it works!

**Comment by barbeau** [comment]
So it looks like `0.0.6` and `0.0.7` are both published now and available on JCenter, but for some reason it's not syncing with Maven Central:
https://bintray.com/mobilitydata/mobilitydata-mvn-repo/gtfs-realtime-bindings

I'll look into this, but for now to use the artifact you can add JCenter as a dependency if it's not there already.

**Pull request merged**
