### PR TITLE
feat: Release version 0.0.8 to Maven Central

### LINKED ISSUE #90: Release version 0.0.8 on Maven Central
Publish release version 0.0.8 on Maven Central as explained [here](https://github.com/MobilityData/gtfs-realtime-bindings/pull/89#discussion_r835299256).

Update the release process as explained [here](https://github.com/MobilityData/gtfs-realtime-bindings/pull/89#discussion_r838873387) at the same time.

### PR DESCRIPTION
**Pull request by maximearmstrong**
Fixes #90 .

- Updates version in `./java/pom.xml` and `./java/README.md`

### CODE REVIEW

**Review by barbeau — COMMENTED** [review]
Thanks @maximearmstrong!

So it looks like we're using the manual release process instead of `mvn release`, which I think is ok (see more of my thoughts on this at https://github.com/MobilityData/gtfs-realtime-bindings/pull/89#discussion_r838873387).

Could you update the release docs to reflect this? Right now they are still a TODO:
https://github.com/MobilityData/gtfs-realtime-bindings/blob/master/java/UPDATING.md#every-release

Also, you didn't need to do anything else with the Sonatype ticket for these changes, right? If not I'd suggest removing the reference to the ticket in the PR description to avoid confusion.

Other than the above this looks good. So on merge the GitHub Action should publish `0.0.8`, and then we'd just need to open a new PR after that updating the version to `0.0.9-SNAPSHOT` and merge that to have the new snapshot ready.

**Comment by maximearmstrong** [comment]
> So it looks like we're using the manual release process instead of `mvn release`, which I think is ok (see more of my thoughts on this at [#89 (comment)](https://github.com/MobilityData/gtfs-realtime-bindings/pull/89#discussion_r838873387)).

Yes, I thought it would be less error prone. More steps, but it seems fair if we can get clearer PRs and commits.

> Could you update the release docs to reflect this? Right now they are still a TODO:
> https://github.com/MobilityData/gtfs-realtime-bindings/blob/master/java/UPDATING.md#every-release

Oh right. Done :)

Also, I think I should create a tag [like this](https://github.com/MobilityData/gtfs-realtime-bindings/tags) on the squashed commit created by merging this PR. Thoughts?

**Review by barbeau — APPROVED** [review]
LGTM, thanks @maximearmstrong!

**Comment by barbeau** [comment]
@maximearmstrong looks like the publish to Maven Central failed on the main branch (401 unauthorized):
https://github.com/MobilityData/gtfs-realtime-bindings/runs/6717799345?check_suite_focus=true

**Pull request merged**
