### PR TITLE
Update python bindings to new proto release

### PR DESCRIPTION
**Pull request by jsa34ito**
Update python bindings to new proto release
Minor change in Python example to be Python3 syntax, not Python2

### CODE REVIEW

**Comment by jsa34ito** [comment]
Probably worth noting, running nosetests failed locally, but not sure if it is an issue with my set up:

E
======================================================================
ERROR: testParseFromString (test_gtfs_realtime_pb2.GtfsRealtimeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/PycharmProjects/gtfs-realtime-bindings/python/tests/test_gtfs_realtime_pb2.py", line 29, in testParseFromString
    feed.ParseFromString(f.read())
  File "/usr/lib64/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 30: invalid continuation byte

-

**Comment by jsa34ito** [comment]
Solved comment above - looks like the unit test needed resolving for the encoding.

I have also added the encoding back into the pb2.py as it looks like it was omitted - if that was the wrong thing to do, let me know, otherwise I think it's good to go

**Comment by axyjo** [comment]
@barbeau any chance you can merge + release on Pypi?

**Comment by barbeau** [comment]
@jsa34ito Thanks for opening this! I went ahead and followed our normal [UPDATING](https://github.com/MobilityData/gtfs-realtime-bindings/blob/master/python/UPDATING.md) process for the Python bindings in https://github.com/MobilityData/gtfs-realtime-bindings/commit/908d049980221a4ec9d1db67bd9f953fbcc366d1. So I'm going to close this out.

@jsa34ito and @axyjo I pushed another release to PyPi:
https://pypi.org/project/gtfs-realtime-bindings/0.0.7/

Please let me know if you have any issues with it!

**Comment by jsa34ito** [comment]
Hello!

I followed this UPDATING process for updating the Python bindings, however the nosetests fail due to encoding issues, hence the additional commit here to resolve that issue.

**Comment by barbeau** [comment]
@jsa34ito Hmm, maybe a platform specific issue? I generated the bindings on Windows 7. The auto-generated bindings should be platform independent and I wouldn't want to edit them manually, but if there need to be changes to the Python test file to run on other OS please feel free to open a pull request with changes.

**Pull request closed without merging**
